"use client"

import { useState } from "react"
import { Whiteboard } from "@/components/whiteboard"
import { ShareNoteDialog } from "@/components/share-note-dialog"
import { Button } from "@/components/ui/button"
import { BrainCircuit } from "lucide-react"
import { QuizModal, type QuizQuestion } from "@/components/quiz-modal"

interface NotePageProps {
  params: {
    id: string
  }
}

export default function NotePage({ params }: NotePageProps) {
  const { id } = params
  const [isQuizOpen, setIsQuizOpen] = useState(false)

  // In a real app, we would fetch the note data from an API
  const note = {
    id,
    title:
      id === "1"
        ? "Project Brainstorm"
        : id === "2"
          ? "Team Meeting Notes"
          : id === "3"
            ? "Product Roadmap"
            : "New Note",
    description: "Collaborative whiteboard for brainstorming and planning.",
  }

  // Sample quiz data - in a real app, this would be generated by AI based on the whiteboard content
  const sampleQuiz: QuizQuestion[] = [
    {
      id: "q1",
      question: "What is the primary goal of a project kickoff meeting?",
      options: [
        { id: "q1a", text: "To assign blame for previous project failures", isCorrect: false },
        { id: "q1b", text: "To establish project objectives and team roles", isCorrect: true },
        { id: "q1c", text: "To determine the project budget only", isCorrect: false },
        { id: "q1d", text: "To schedule future meetings", isCorrect: false },
      ],
      explanation:
        "A project kickoff meeting primarily serves to align the team on objectives, clarify roles and responsibilities, and establish communication protocols for the project.",
    },
    {
      id: "q2",
      question: "Which of the following is NOT typically included in a project roadmap?",
      options: [
        { id: "q2a", text: "Timeline of deliverables", isCorrect: false },
        { id: "q2b", text: "Key milestones", isCorrect: false },
        { id: "q2c", text: "Detailed personal vacation schedules", isCorrect: true },
        { id: "q2d", text: "Dependencies between tasks", isCorrect: false },
      ],
      explanation:
        "Project roadmaps typically include timelines, milestones, dependencies, and high-level resource allocation, but not detailed personal schedules like vacations, which would be tracked separately.",
    },
    {
      id: "q3",
      question: "What does the acronym 'MVP' stand for in product development?",
      options: [
        { id: "q3a", text: "Most Valuable Professional", isCorrect: false },
        { id: "q3b", text: "Multiple Version Product", isCorrect: false },
        { id: "q3c", text: "Minimum Viable Product", isCorrect: true },
        { id: "q3d", text: "Maximum Value Proposition", isCorrect: false },
      ],
      explanation:
        "MVP stands for Minimum Viable Product, which is the version of a product with just enough features to be usable by early customers who can then provide feedback for future development.",
    },
    {
      id: "q4",
      question: "Which brainstorming technique involves building on others' ideas?",
      options: [
        { id: "q4a", text: "Mind mapping", isCorrect: false },
        { id: "q4b", text: "SWOT analysis", isCorrect: false },
        { id: "q4c", text: "Brainwriting", isCorrect: false },
        { id: "q4d", text: "Piggyback brainstorming", isCorrect: true },
      ],
      explanation:
        "Piggyback brainstorming is a technique where participants build upon or 'piggyback' on the ideas of others, leading to collaborative idea development and refinement.",
    },
    {
      id: "q5",
      question: "What is a 'sprint' in Agile project management?",
      options: [
        { id: "q5a", text: "A race between team members", isCorrect: false },
        { id: "q5b", text: "A fixed time period for completing a set of tasks", isCorrect: true },
        { id: "q5c", text: "A type of emergency meeting", isCorrect: false },
        { id: "q5d", text: "A software bug", isCorrect: false },
      ],
      explanation:
        "In Agile methodology, a sprint is a fixed time period (typically 1-4 weeks) during which a specific set of work must be completed and made ready for review.",
    },
  ]

  return (
    <div className="h-full w-full flex flex-col">
      <div className="flex justify-between items-center mb-4">
        <div>
          <h1 className="text-2xl font-bold">{note.title}</h1>
          <p className="text-muted-foreground">{note.description}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setIsQuizOpen(true)} className="gap-2">
            <BrainCircuit className="h-4 w-4" />
            Generate Quiz
          </Button>
          <ShareNoteDialog noteId={id} />
        </div>
      </div>
      <div className="flex-1 border rounded-lg overflow-hidden w-full">
        <Whiteboard />
      </div>

      <QuizModal
        open={isQuizOpen}
        onOpenChange={setIsQuizOpen}
        title={`Quiz on ${note.title}`}
        questions={sampleQuiz}
      />
    </div>
  )
}

